apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    environment: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend
  labels:
    app: frontend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: react
        image: 853973692277.dkr.ecr.us-east-1.amazonaws.com/ns2312-fe-repo-1:release3
        resources:
          limits:
            memory: "100Mi"
            cpu: "300m"
        ports:
        - containerPort: 80

      imagePullSecrets:
      - name: frontend-ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
spec:
  selector:
    app: frontend-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-ecr-secret
  namespace: frontend
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSI4NTM5NzM2OTIyNzcuZGtyLmVjci51cy1lYXN0LTEuYW1hem9uYXdzLmNvbSI6IHsKCQkJImF1dGgiOiAiUVZkVE9tVjVTbmRaV0d4ellqSkdhMGxxYjJsVWEwVXlXV3RuZDFadFZrbGFWelZHWWpCYVVsRldXbUZTTUdoNFdsaEtiMlF6WjNsTlZteEpWRWhhYVZJd1RtOVNNVm95WkVkS01HUXhTbGxWTW1NelRrVm9WbUpFVW5KT2VrSndVMVZTYUdORlpGZE9WR014VmtkRmVtVnFhRlpMZWswelYycFNjMVp0YkZkaWEzaFRWRVJOTldWWE1VSlZhMmgyVlVjeFVWa3pUbmhVVldSVldUTktlVmxUZEhWVVYwMTJZbXhhVVdWdFp6VldXRTVLWkZSa1MyVlliRTlXVlc5M1VWVlNWV0ZUT1ZKa1JFcG9UV3RLVUVzd1NscFRiVTQwVjBVeGFHRnFTbTVSVm1oYVRqQnNlVnBFU25OU1dHZ3pVa2RzZEZsVVJtRk5SV1JaV1c1U1RXVnRNWEJVTWtvMFZFVTVhMVZFU25GT00xVjJZMGM0ZUZaNlpHMVpiV3cwVEROc1dGTnRPWGhYYVhSeFZHazVkRmxYWnpSVWEyUnZZa1ZzTVdWR1pERlViVGh5VFVkc1ZWUklRVEJhYlU0MlkwUlNhbEpzUW5sYWJGcDZUakI0YVZOVk1ERmliVkpJWlZjeE1WWXlaM2xsV0ZaVllWaHdjV0ZXVG0xbFIwcHFVMjFvYkdJd1ZuTk5WVlpWWW14d1drMUZWa3RpZW1RMFZHNUtXbFpyZEVSUmJXZHlaRmRPZDFKdVJucFhiR1JHWTBWV2FrMUhiSFZaVmxwc1pHNU9RbHBFYURCaWJVcGhVVEJXUjFZeWNFcFZNakF3VFRGTk0xZHVRbTFhTUhoTFVsUktOVkpJUVhkaFJWSjFVVEZDYVZSV1dUVlZTR2h5WVcwMVVWa3lOVkJhTUhSaFRXNVNXVnBYVWtoalJFcHVUakJvZWxZemNFNVNiV3h5VmxaQ1VGWlRPVEpXU0d4UVRVaGtka3N3V2pWWlZFMTVVVEZSZWxOdVVqUlpWa0pHVjBkb2RsWXhTa0pYYkd4TlpGZGtkMVZ0WTNkUldHeHRWbXQwYWxOSVVUUlRlazVEVmtNNGVVMVZaRXhrYW1SM1VXeGFOR0pWTVRGWFNHeDFXbTA0TVZkSGJFdFVTRnB1WWtkV2Rsa3lOVnBVV0dSSVpHczFTbFJ1V25kTlJrcG9XVmhHUWxORmNHNWlSWFI1V2xkNE5rMVhXbEJWYms0MlRERmtkVlJWTld4V1JXaDZWMVZXTWswd1duWlVSRUpGVkRCa1dsbFhjR0ZqVjFvMlN6RkdVR0pITlZwaFdHeHFWRlUxVDFOSFRqVlVNbVJXWTJ0U1dHVlRPWGRaVlZFd1QwVmFkbE13U1RWU1YyY3hZbXRvVTFGVWFIUlNha0p2WXpKS1JWbHFSbTFVUnpGeFkxVXhhMUZyV2xKU2JtUnZWRVpzUkZOV1ZsaExNRkpFVkZjMVNWTXljekpYUlU1cFRrVldjazE2UWxGaFYzUnFZVlJXZDFGdGFERmpSMnQzWVZob2FtVkdSa1ZXUlVwWlZtdGFibU5FU1hkV1YwcHRUVzFHVVdJelFtMVJNM0JaVlZoQ1IxVkVSVEZOUkU1dllXMWFUR0l5V25kTk1FbDVaR3N4VEdWdVNuWlRVemt6WkZkNFVGVnVXbnBUVkdneFRsWkdjVkpJYkZSUmFsSnRVMFZzTldKcmFFcGFSMnhOWTFoR1ExSkViRU5aYTFwV1pGaENibHB1V2pGU1JrNTRZbTAxUzFSSE1UVmhWVlY2WXpCV2ExbFdWbGRYUnpBMVRWWmtiV0l3VG10aVZVWlhZbXRrV2xReGJIcFZSbGx5VTBoQ2VHSlhjRE5OV0VwVFVWY3hTbGxxU2xwWk1taFlVV3M1TUdOcmJEWlZWMk16Vkc1T1NsVXdNRFJPVlRFeVYxTTVWVlZZWkZOYWFUa3lTekF4ZUZkWVZUVlpNREZhV1RCd2JWRXpTa0pqYWxKdVpHNVdlV0pXVVhoVlZWbDVXbTB3TkUxRk5XcFNWV1F3VlZoV1ZGZFhXakpWUlZKcVkxY3hObFJ0VlhkU1dHUnRaVlJHY21SWFRtdFdTRUkyVW0xb05HSnBkSEJXUm14MlVWaHNiRTVxU25GU00yUkRWbFZhUWxNeFVrNU5NV2hUVGpGb1dGVlhVWGhOTVZwT1YwUnNUR0pWY0cxU1JFVjJUVmhOTkZreWQzaFVhbXd5VjBodmQxZFhSbHBqVmxZeVlURmFhRlo2U25sa2JYUjNaRVZrYzFSclNsUmFNRlpXV1RGb2NWSldSbXRYYlhRelZsVjRVMUZyVW5KV1ZtUXhVMFZyTTJSNldrSlVXR2hTWW14T1EwNVlRa05aTVVwWldrWkNWRkpxU2pCWlZrNUZXVEpXZGxJeVVuRmxia0pEVGxkMFNWVkdXbFpYYld4eVVWaE9TMUZWWTNsT1NHaEZZVEZTYVV3eFJqQk9ia1pRV2tSUmRsSXlPSGRsYlU1VlZFZFplbFZGWXpGVk1VNVNWMjFrYTFWVmNIQmlWMDVHVVZjME5GWjZRbGxpUmtaNVZXMXdVbFZVU2sxVldIQkpWa1U1YkZGWVFtaGhTRkYyWVd4cmRtVlhWbmRqUms1SVdteGpNVkV5YUVaa01HUnBaVmRTVTFGVVRuaGFWVXBKWTJwT1NGbFVWbEZrTVZreFRUTk5lR1ZZYUdGTk0yTnlWRzFKZGxwdGNGUlpWVkozVGxkbmVFMVdhRUpXUmtreFlWaFNORlJ1Y0hkbFZsVXhXa2RTYzFKSFVuZFJhMXBhVFVWU1ZGWlZjRlpsUm1NMVlXNUdVR0pJY0ZsVmJGSjJXa2h3TVZaWVNsbFRSRWw1VERGV1dGWklaSGxWYkZKT1lsaGFUVTVIYUhaaVYzY3dZbnBLV0ZKcldreE5SMVYzVm01c2QxVXlUbmhhTTBKWVdsUktNMWRZVG5kT1IwMXlUbFUxTWxaV1pHRlRNa1V5WVhwU2NsWlZTbEJTTURsUVZETlNUMkl5YkRKaFJtZzJUVEJvUzJSSVpGVlNSa294VlRJNWNVc3lkRXhWV0VaYVdtMTRWV0pJWXpKa00xb3pXVlJhUldJeFRrTlNiVkl3VVdwQ1VWZFZSbmxrV0ZGNFkyMTBibUZVV2xCUlYxWlJXbTFHTWxsWGQzWlBXRUpQVmtWMFExWllVa2RVTWs0MVUwaHNlbFJxUmtoYWJuQXdUVmhXU2sxWVNUVldiV3d4VTFoRmVsWXlNVnBoVkVaU1ltazVVVkZzUmxSalJWVjNXbFZyZVdGWE1VbGpXRVV3VTJ4VmQxTkZhRkpVVlRGVVpVWk5jbFp1UWpOWlYwVjZaRVJzVWxCVU1HbE1RMHByV1ZoU2FHRXlWalZKYW05cFVWWkdSbEZyUmtsaFNHUjBUVVpzYUZOV1RrdGFWa293VTIwd01XSnFSa2hPYmxaNFdsZFdjbGRJVm5aWFJtaFJXbFJXVmxKdFRteFBWa3A0VDBNNGVFNUlaRUpSVlVaSlRraGtiVkZXYkV0VE1qbGhVMWRvTWxrd05VSlZWMDVJWWpCak5HUXlTbEpUVlVwQ1VrVktkbEZ0WkhKalYyaHlZVlZqTldSNlFrTlJibVJHWkRCb2JsZFZjRnBUVm5CS1VWWmtWbEpGU2tKU1dGWk9VV3RXUmxKRldtOWtiVWw0V25wb05tVnNWbXhSYW1oTVUwZEdibE5WU2taVFZVVXpWa2RyZVZwRVZqQmhTRVYzWVdwa2IyRlRkRTlhZWtaWVlqQTVSVk5JYkZSU00wRjJVMjF3TmsweGJIaFBXRlpGVmxkU01FNUZTa1ZUUkdoMFkwZGthV051UWxSYU1VWkVWRWRrVWxSclJqUlpiR3MwWlZaVk5WbFZUWHBpU0U1UFRWYzVhazFWY3pGamVqQnBURU5LTWxwWVNucGhWemwxU1dwdmFVMXBTWE5KYmxJMVkwZFZhVTlwU2tWUlZsSkNXREIwUmxkVFNYTkpiVlkwWTBkc2VWbFlVbkJpTWpScFQycEZNMDE2VVRSTlJGVXhUMVJvT1E9PSIKCQl9Cgl9Cn0=
